name: DAST

on:
  #push:
  #  branches:
  #  - main
  #pull_request:
  #  branches:
  #  - main
  workflow_dispatch:
    branches: 
    - main

jobs:
  lint:
    name: DAST
    runs-on: self-hosted
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: pull the image
        run: docker pull owasp/zap2docker-stable
      - name: run the scan
        run: docker run -t owasp/zap2docker-stable zap-baseline.py -t http://${{secrets.TEST_WEB_SERVER}}:3000
        continue-on-error: true
      - name: Upload the OWASP ZAP report
        uses: actions/upload-artifact@v2
        with:
          name: owasp-zap-report
          path: ./report_html.html
