name: OWASP Dependency Checker
    
on:
#  push:
#    branches:
#    - main
#  pull_request:
#    branches:
#    - main
  workflow_dispatch:
    branches: 
    - main

jobs:
  lint:
    name: OWASP Dependency Checker
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run npm install
        run: npm install
    
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          others: ''
        
      - name: Upload the OWASP dependency check report
        uses: actions/upload-artifact@v2
        with:
          name: owasp-dependency-check-report
          path: ./reports
