name: SonarCloud SAST
    
on:
#  push:
#    branches:
#    - main
#  pull_request:
#    branches:
#    - main
  workflow_dispatch:
    branches: 
    - main

jobs:
  lint:
    name: sonar
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
            args: >
              -Dsonar.organization=coffeebeast
              -Dsonar.projectKey=astuto     
