name: Trufflehog Sensitive Information Scan
    
on:
#  push:
#    branches:
#    - main
#  pull_request:
#    branches:
#    - main
  workflow_dispatch:
    branches: 
    - main

jobs:
  lint:
    name: Trufflehog
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2     
              
      - name: Trufflehog Actions Scan
        uses: edplato/trufflehog-actions-scan@v0.9k-beta
        with:
          scanArguments: "-x trufflehog_excludes --entropy false"
        continue-on-error: true
